### ISSUE TITLE
Dependency bot keeps pinging me

### ISSUE THREAD

**Issue by greggb** [davegaeddert/dotfiles-1#28]
Hey, whenever your bot updates hyperlinks it mentions me in the notes. Anyway you could turn that off? Thanks.

**Comment by davegaeddert** [comment]
Oh wow, sorry about that @greggb. I'm testing some stuff out here for dependencies.io and it's just inserting the notes exactly as they were written in that release. I'll see if we can get those mentions taken out somehow across our whole platform... Thanks for saying something!

**Comment by greggb** [comment]
Not a problem - I thought that might be the case. I ignored the repo for now.
